"""inicial edital

Revision ID: inicial_edital_20260910
Revises:
Create Date: 2026-09-10 14:12:11.516938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'inicial_edital_20260910'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_ref', sa.Date(), nullable=False),
    sa.Column('canais', sa.String(length=120), nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resumo', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digest_log_data_ref'), 'digest_log', ['data_ref'], unique=False)
    op.create_table('edital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('chave_natural', sa.String(length=200), nullable=False),
    sa.Column('hash_conteudo', sa.String(length=64), nullable=False),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('orgao_nome', sa.String(length=300), nullable=False),
    sa.Column('orgao_cnpj', sa.String(length=20), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('municipio', sa.String(length=200), nullable=True),
    sa.Column('modalidade', sa.String(length=120), nullable=True),
    sa.Column('valor_estimado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=True),
    sa.Column('data_abertura', sa.Date(), nullable=True),
    sa.Column('data_fim_propostas', sa.Date(), nullable=True),
    sa.Column('score_relevancia', sa.Float(), nullable=False),
    sa.Column('motivo_relevancia', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('url_origem', sa.Text(), nullable=False),
    sa.Column('capturado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fonte', 'chave_natural', name='uq_edital_fonte_chave')
    )
    op.create_index(op.f('ix_edital_data_publicacao'), 'edital', ['data_publicacao'], unique=False)
    op.create_index(op.f('ix_edital_fonte'), 'edital', ['fonte'], unique=False)
    op.create_index(op.f('ix_edital_score_relevancia'), 'edital', ['score_relevancia'], unique=False)
    op.create_index(op.f('ix_edital_status'), 'edital', ['status'], unique=False)
    op.create_table('execucao_captura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('janela_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('janela_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_lidos', sa.Integer(), nullable=False),
    sa.Column('total_novos', sa.Integer(), nullable=False),
    sa.Column('total_relevantes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('erro', sa.Text(), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execucao_captura_fonte'), 'execucao_captura', ['fonte'], unique=False)
    op.create_table('projeto_interesse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('palavras_chave', sa.JSON(), nullable=False),
    sa.Column('filtros', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arquivo_edital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edital_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('caminho_local', sa.Text(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('baixado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edital_id'], ['edital.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arquivo_edital')
    op.drop_table('projeto_interesse')
    op.drop_index(op.f('ix_execucao_captura_fonte'), table_name='execucao_captura')
    op.drop_table('execucao_captura')
    op.drop_index(op.f('ix_edital_status'), table_name='edital')
    op.drop_index(op.f('ix_edital_score_relevancia'), table_name='edital')
    op.drop_index(op.f('ix_edital_fonte'), table_name='edital')
    op.drop_index(op.f('ix_edital_data_publicacao'), table_name='edital')
    op.drop_table('edital')
    op.drop_index(op.f('ix_digest_log_data_ref'), table_name='digest_log')
    op.drop_table('digest_log')
    # ### end Alembic commands ###
